Arrays VS List

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3, 4, 5]

In [3]:
A = np.array([1, 2, 3, 4, 5]) # or np.array(L)

In [4]:
for i in L: 
    print(i, end=' ')

1 2 3 4 5 

In [6]:
for i in A: 
    print(i, end=' ')

1 2 3 4 5 

In [8]:
L.append(6)  # Adding an element to the list
L

[1, 2, 3, 4, 5, 6, 6]

In [ ]:
#A.append(6)  # This will raise an error because numpy arrays have fixed size
L + [7]  # This creates a new list with the element added
L

[1, 2, 3, 4, 5, 6, 6]

In [ ]:
A + np.array([6])  # This creates a new array with the element added, this is valid and called as broadcasting
# broadcasting is a powerful feature in numpy that allows operations on arrays of different shape and sizes

array([ 7,  8,  9, 10, 11])

In [ ]:
A + np.array([6,7]) # This will raise an error because the shapes are not compatible for broadcasting`

SyntaxError: invalid syntax (971608288.py, line 1)

In [16]:
A + np.array([6,7,8,9,10]) # this will not raise an error and because both the arrays have same shape

array([ 7,  9, 11, 13, 15])

In [19]:
2 * A  # This will multiply each element of the array by 2


array([ 2,  4,  6,  8, 10])

In [ ]:
2 * L  # This will do the repeatition of the list


[1, 2, 3, 4, 5, 6, 6, 1, 2, 3, 4, 5, 6, 6]

In [22]:
L + L # This will concatenate the list with itself

[1, 2, 3, 4, 5, 6, 6, 1, 2, 3, 4, 5, 6, 6]

In [24]:
L2 = []
for i in L:
    L2.append( i + 3)
L2  # This will create a new list with each element incremented by 3

[4, 5, 6, 7, 8, 9, 9]

In [26]:
L2  = [i + 3 for i in L]
L2  # This will create a new list with each element incremented by 3 using list comprehension

[4, 5, 6, 7, 8, 9, 9]

In [30]:
L ** 2 # This will raise an error because lists do not support element-wise operations

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [28]:
L2 = []
for i in L:
    L2.append( i ** 2) # This will create a new list with each element squared

L2

[1, 4, 9, 16, 25, 36, 36]

In [29]:
A**2  # This will square each element of the array

array([ 1,  4,  9, 16, 25])

In [31]:
np.sqrt(A)  # This will take the square root of each element of the array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [33]:
np.log(A)  # This will take the natural logarithm of each element of the array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [32]:
np.exp(A)  # This will take the exponential of each element of the array

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])