In [3]:
import numpy as np

In [ ]:
np.zeros((3, 3))  # Example usage of numpy
# This code initializes a 3x3 array of zeros using numpy.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2, 2))  # Example usage of numpy
# This code initializes a 2x2 array of ones using numpy.

array([[1., 1.],
       [1., 1.]])

In [6]:
10 * np.ones((2, 2))  # Example usage of numpy
# This code initializes a 2x2 array of tens using numpy.

array([[10., 10.],
       [10., 10.]])

In [7]:
np.eye(3)  # Example usage of numpy
# This code creates a 3x3 identity matrix using numpy.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((2,3))  # Example usage of numpy
# This code generates a 2x3 array of random numbers using numpy.
# the range is between 0 and 1.

array([[0.807398  , 0.89959723, 0.23318813],
       [0.02652273, 0.62436987, 0.83360098]])

In [10]:
np.random.randn(2, 3)  # Example usage of numpy
# This code generates a 2x3 array of random numbers from a standard normal distribution using numpy.
# the range is between -1 and 1.

array([[-0.33342201, -0.06178175, -0.15479259],
       [ 0.90169324,  0.06908403, -0.7634822 ]])

In [11]:
R = np.random.randn(10000) 
# This code generates an array of 10,000 random numbers from a standard normal distribution using numpy.

In [12]:
R.mean()

np.float64(0.005373532523172202)

In [ ]:
np.mean(R) # This code calculates the mean of the array R, which contains random numbers from a standard normal distribution.

np.float64(0.005373532523172202)

In [16]:
R.var()

np.float64(0.9991160444152883)

In [17]:
R.std()

np.float64(0.9995579244922669)

In [22]:
R = np.random.randn(1000, 3)  # Example usage of numpy
# This code generates a 1000x3 array of random numbers from a standard normal distribution using numpy.

In [23]:
R.mean(axis=0)  # Example usage of numpy

array([-0.02916153,  0.00720028,  0.02319399])

In [24]:
R.mean(axis=1)  # Example usage of numpy
# This code calculates the mean of each row in the array R, which contains random numbers from a standard normal distribution.

array([ 7.22469761e-01,  1.89476569e-01,  7.02908391e-01, -5.36400032e-01,
        2.02328316e-01,  4.36961956e-01, -1.48451673e-01, -1.89692751e+00,
       -3.78008694e-01,  8.31529520e-02, -3.72632076e-01,  2.45087567e-01,
       -1.12801637e-01, -3.10028727e-01,  2.52086906e-01,  5.60451723e-01,
       -1.59771242e-01,  3.49402762e-02, -1.11336991e-03,  7.09283347e-01,
        8.72911763e-01,  8.55952526e-02, -9.66168728e-01,  3.12035153e-01,
        9.16353175e-01,  3.31670437e-01, -7.18992268e-01,  1.24620453e+00,
        9.91470678e-01, -6.12965030e-01,  5.44877059e-01,  9.15614225e-01,
       -3.70531963e-01, -1.37570996e-01, -1.39584421e-01,  4.18635782e-01,
        2.69465264e-01, -6.49642732e-02, -8.54617226e-02,  9.58217762e-01,
       -1.05753758e+00, -2.60953378e-02,  3.84905759e-01, -7.33708433e-01,
        6.43687683e-01,  7.34360226e-01,  3.91212586e-01, -1.30753800e+00,
        4.19762368e-02, -5.79208054e-01, -3.95257161e-01,  3.43950617e-01,
        3.01418573e-01,  

In [25]:
R.mean(axis = 1).shape  # Example usage of numpy
# This code returns the shape of the array obtained by calculating the mean of each row in the array R, which contains random numbers from a standard normal distribution.
# The shape will be (1000,) since it calculates the mean across the columns for each row.

(1000,)

In [26]:
np.cov(R)  # Example usage of numpy
# This code calculates the covariance matrix of the array R, which contains random numbers from a standard normal distribution.
# The covariance matrix provides insights into the relationships between the different columns of the array.

array([[ 0.60235715, -1.37380581,  0.53089597, ..., -0.85797299,
         0.53203998, -0.13146004],
       [-1.37380581,  3.20303033, -0.83787661, ...,  2.20385369,
        -1.09247194,  0.49623845],
       [ 0.53089597, -0.83787661,  2.46148045, ...,  0.56446442,
         1.11550873,  0.93406495],
       ...,
       [-0.85797299,  2.20385369,  0.56446442, ...,  2.09693499,
        -0.32948009,  0.88277819],
       [ 0.53203998, -1.09247194,  1.11550873, ..., -0.32948009,
         0.67964374,  0.22441702],
       [-0.13146004,  0.49623845,  0.93406495, ...,  0.88277819,
         0.22441702,  0.58164412]], shape=(1000, 1000))

In [ ]:
np.cov(R).shape  # Example usage of numpy
# This code returns the shape of the covariance matrix calculated from the array R, which contains random numbers from a standard normal distribution.

(1000, 1000)

In [28]:
np.cov(R.T)  # Example usage of numpy
# This code calculates the covariance matrix of the transposed array R, which contains random numbers from a standard normal distribution.

array([[ 0.96862911,  0.01520246, -0.01524415],
       [ 0.01520246,  0.96178883, -0.02791356],
       [-0.01524415, -0.02791356,  1.03775644]])

In [29]:
np.cov(R, rowvar=False)  # Example usage of numpy
# This code calculates the covariance matrix of the array R, treating each column as a variable and each row as an observation.
# The `rowvar=False` argument indicates that the rows represent observations rather than variables.
# This is useful when the data is structured such that each column represents a different variable, and each row represents a different observation.
# The covariance matrix provides insights into the relationships between the different variables in the dataset.

array([[ 0.96862911,  0.01520246, -0.01524415],
       [ 0.01520246,  0.96178883, -0.02791356],
       [-0.01524415, -0.02791356,  1.03775644]])

In [31]:
np.random.randint(0,10, size=(2, 3))  # Example usage of numpy
# This code generates a 2x3 array of random integers between 0 and 10 using numpy.
# The `ranint` function is used to generate random integers, and the `size` parameter specifies the shape of the output array.

array([[3, 2, 4],
       [2, 7, 7]])

In [32]:
np.random.choice(10 , size=(2, 3))  # Example usage of numpy
# This code generates a 2x3 array of random integers between 0 and 9 using numpy.
# The `choice` function is used to randomly select elements from the specified range,
# and the `size` parameter specifies the shape of the output array.

array([[6, 5, 6],
       [6, 8, 0]])