In [1]:
import numpy as np

In [2]:
L = [[1,2],[3,4]] # This is a 2D list (matrix) in Python, where each inner list represents a row of the matrix.

L

[[1, 2], [3, 4]]

In [6]:
L[0] # This accesses the first row of the matrix, which is [1, 2]



[1, 2]

In [7]:
L[1] # This accesses the second row of the matrix, which is [3, 4]

[3, 4]

In [8]:
L[0][1] # This accesses the element in the first row and second column of the matrix, which is 2

2

In [10]:
A = np.array(L)  # This converts the 2D list into a NumPy array, which is a more efficient way to handle matrices in Python

A

array([[1, 2],
       [3, 4]])

In [11]:
A[0][1] # This accesses the element in the first row and second column of the NumPy array, which is 2

np.int64(2)

In [12]:
A[1, 0] # This accesses the element in the second row and first column of the NumPy array, which is 3

np.int64(3)

In [ ]:
A[:, 0] # This accesses all rows in the first column of the NumPy array, which is [1, 3], : means select everything in that dimentionm=, that is all rows in just in first column, defined by 0

array([1, 3])

In [ ]:
A.T # This transposes the matrix, swapping rows and columns, resulting in [[1, 3], [2, 4]]

array([[1, 3],
       [2, 4]])

In [15]:
np.exp(A) # This applies the exponential function to each element of the matrix, resulting in a new matrix with the same shape where each element is e raised to the power of the corresponding element in A

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [17]:
np.exp(L) # This will not raise an error, as numpy already know what list represents and treat it as a numpy array, so it will apply the exponential function to each element of the matrix, resulting in a new matrix with the same shape where each element is e raised to the power of the corresponding element in L

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [18]:
B =  np.array([[1,2,3],[4,5,6]]) # This is a 2D list (matrix) in Python, where each inner list represents a row of the matrix.  

B

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
A.dot(B) # This performs matrix multiplication between A and B, resulting in a new matrix where each element is the dot product of the corresponding row of A and column of B. The result will be a 2x3 matrix.

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [21]:
B.dot(A) # This will raise an error, as the dimensions of B and A are not compatible for matrix multiplication. B is a 2x3 matrix and A is a 2x2 matrix, so they cannot be multiplied directly.

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
np.linalg.det(A) # This computes the determinant of the matrix A, which is a scalar value that can be used to determine if the matrix is invertible (non-zero determinant means it is invertible).

np.float64(-2.0000000000000004)

In [23]:
np.linalg.inv(A) # This computes the inverse of the matrix A, which is a matrix that, when multiplied by A, results in the identity matrix. The inverse exists only if A is square and non-singular (i.e., its determinant is not zero).

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
np.linalg.inv(A).dot(A) # This computes the inverse of the matrix A and then multiplies it by A, resulting in the identity matrix. This is a way to verify that the inverse was computed correctly, as multiplying a matrix by its inverse should yield the identity matrix.

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [26]:
np.trace(A) # This computes the trace of the matrix A, which is the sum of the diagonal elements. For A, it will be 1 + 4 = 5.

np.int64(5)

In [27]:
np.diag(A) # This extracts the diagonal elements of the matrix A, resulting in a 1D array containing the diagonal elements [1, 4].

array([1, 4])

In [ ]:
np.diag([1,2]) # This creates a diagonal matrix with the elements 1 and 2 on the diagonal, resulting in a 2x2 matrix [[1, 0], [0, 2]].

array([[1, 0],
       [0, 2]])

In [31]:
np.linalg.eig(A) # This computes the eigenvalues and eigenvectors of the matrix A. The eigenvalues are the scalars that indicate how much the eigenvectors are stretched or compressed during the linear transformation represented by A. The result will be a tuple containing an array of eigenvalues and a 2D array of eigenvectors.

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [32]:
Lam, V = np.linalg.eig(A) # This computes the eigenvalues and eigenvectors of the matrix A. The eigenvalues are stored in Lam and the eigenvectors are stored in V. The eigenvectors are the directions in which the matrix A stretches or compresses space, and the eigenvalues indicate how much stretching or compressing occurs along those directions.

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0] # This checks if the first eigenvector scaled by its corresponding eigenvalue is equal to the product of A and the first eigenvector. This is a property of eigenvectors and eigenvalues, where A applied to an eigenvector results in the eigenvector scaled by its eigenvalue.

# this is not a correcct way as follow

array([ True, False])

In [34]:
V[:,0] * Lam[0] , A @ V[:,0] # This shows the left-hand side (the first eigenvector scaled by its eigenvalue) and the right-hand side (the product of A and the first eigenvector) separately, which should be equal if the eigenvalue and eigenvector are correct. If they are not equal, it indicates a mistake in the computation or understanding of eigenvalues and eigenvectors.

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
# Coorect way to check if the eigenvalue and eigenvector are correct is to use the following:

np.allclose(V[:,0] * Lam[0], A @ V[:,0]) # This checks if the first eigenvector scaled by its corresponding eigenvalue is approximately equal to the product of A and the first eigenvector, allowing for numerical precision errors. If this returns True, it confirms that the eigenvalue and eigenvector are correct.



True