In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sbux.csv')


In [3]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [7]:
df.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume','Name']

In [8]:
df.head()

Date    Open    High     Low   Close   Volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [9]:
df['Open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: Open, Length: 1259, dtype: float64

In [11]:
df[['Open','Volume']]

Open    Volume
0     27.920   7146296
1     28.260   5457354
2     28.000   8665592
3     28.230   7022056
4     27.765   8899188
...      ...       ...
1254  56.280  14690146
1255  55.900  15358909
1256  55.530  16059955
1257  53.685  17415065
1258  55.080  13927022

[1259 rows x 2 columns]

In [12]:
type(df[['Open','Volume']])

pandas.core.frame.DataFrame

In [13]:
df.iloc[0]

Date      2013-02-08
Open           27.92
High          28.325
Low            27.92
Close         28.185
Volume       7146296
Name            SBUX
Name: 0, dtype: object

In [14]:
df.loc[0]

Date      2013-02-08
Open           27.92
High          28.325
Low            27.92
Close         28.185
Volume       7146296
Name            SBUX
Name: 0, dtype: object

In [17]:
df2 = pd.read_csv('sbux.csv', index_col='date')

In [18]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [20]:
df2.loc['2013-02-13']

open        28.23
high        28.23
low         27.75
close      27.915
volume    7022056
Name         SBUX
Name: 2013-02-13, dtype: object

In [21]:
type(df2.loc['2013-02-13'])

pandas.core.series.Series

In [23]:
df[df['Open'] > 64]

Date   Open    High    Low  Close   Volume  Name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [26]:
df[df['Name'] != 'SBUX']

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Name]
Index: []

In [27]:
type(df['Name'] != 'SBUX')

pandas.core.series.Series

In [28]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [30]:
df.values

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      shape=(1259, 7), dtype=object)

In [32]:
A = df[['Open', 'Volume']].values
A

array([[2.7920000e+01, 7.1462960e+06],
       [2.8260000e+01, 5.4573540e+06],
       [2.8000000e+01, 8.6655920e+06],
       ...,
       [5.5530000e+01, 1.6059955e+07],
       [5.3685000e+01, 1.7415065e+07],
       [5.5080000e+01, 1.3927022e+07]], shape=(1259, 2))

In [33]:
type(A)

numpy.ndarray

In [35]:
smalldf = df[['Open', 'Volume']]
smalldf.to_csv('smalldf.csv')

In [36]:
!head smalldf.csv

,Open,Volume
0,27.92,7146296
1,28.26,5457354
2,28.0,8665592
3,28.23,7022056
4,27.765,8899188
5,27.805,18195730
6,27.18,11760912
7,27.3,12472506
8,26.535,13896450


In [37]:
smalldf.to_csv('smalldf.csv', index=False)

In [38]:
! head smalldf.csv

Open,Volume
27.92,7146296
28.26,5457354
28.0,8665592
28.23,7022056
27.765,8899188
27.805,18195730
27.18,11760912
27.3,12472506
26.535,13896450
